spring:
  datasource:
    url: jdbc:h2:mem:credit_application_system_db
    username: admin
    password:
  jpa:
    show-sql: true
    hibernate:
      properties:
         hibernate.format_sql: true
#      ddl-auto:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false